export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const GET_ARITST = 'GET_ARITST';
export const GET_ARTIST_TOP_TRACKS = 'GET_ARTIST_TOP_TRACKS';
export const GET_ARTIST_TOP_ALBUMS = 'GET_ARTIST_TOP_ALBUMS';
export const LOAD_TOP_ALBUMS = 'LOAD_TOP_ALBUMS';
export const SET_LOADING = 'SET_LOADING';
export const APP_LAYOUT_ERROR = 'APP_LAYOUT_ERROR';